# Generated by Django 6.0.7 on 2026-08-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_current_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_link',
            field=models.URLField(blank=True),
        ),
    ]
